#include "../runtime/recorder_source.h"
#include "../runtime/combat_stats.h"
#include <cassert>
#include <iostream>
template<class T> void put(uintptr_t p,T v){std::memcpy(reinterpret_cast<void*>(p),&v,sizeof(v));}
int main(){
 std::array<unsigned char,32> h{};auto a=reinterpret_cast<uintptr_t>(h.data());std::memcpy(h.data(),"hello",5);put(a+16,size_t(5));put(a+24,size_t(15));assert(ssc_rpc::native_string(a)=="hello");
 std::string large(128,'a');put(a,reinterpret_cast<uintptr_t>(large.data()));put(a+16,size_t(128));put(a+24,size_t(128));assert(ssc_rpc::native_string(a)==large);
 put(a+16,size_t(129));assert(ssc_rpc::native_string(a).empty());put(a+16,size_t(17));put(a+24,size_t(16));assert(ssc_rpc::native_string(a).empty());put(a+24,size_t(128));put(a,uintptr_t(1));assert(ssc_rpc::native_string(a).empty());
 auto pages=static_cast<unsigned char*>(VirtualAlloc(nullptr,8192,MEM_RESERVE|MEM_COMMIT,PAGE_READWRITE));assert(pages);DWORD old;assert(VirtualProtect(pages+4096,4096,PAGE_NOACCESS,&old));put(a,reinterpret_cast<uintptr_t>(pages+4090));put(a+16,size_t(16));assert(ssc_rpc::native_string(a).empty());assert(ssc_rpc::native_string(reinterpret_cast<uintptr_t>(pages+4080)).empty());VirtualFree(pages,0,MEM_RELEASE);
 auto base=reinterpret_cast<uintptr_t>(VirtualAlloc(nullptr,0x1000000,MEM_RESERVE|MEM_COMMIT,PAGE_READWRITE));std::vector<unsigned char> world(0xb000);auto w=reinterpret_cast<uintptr_t>(world.data());put(base+0xddb5d0,w);put(w+0x128,6);put(w+0x46c,3);put(w+0x3e0,1);assert(!ssc_record::active_round(base,2));for(int i=2;i<=4;++i){put(w+0x3e0,i);assert(ssc_record::active_round(base,2));}put(w+0x3e0,5);assert(!ssc_record::active_round(base,2));put(w+0x3e0,4);put(w+0x3c0,2.f);assert(!ssc_record::active_round(base,2));put(w+0x3c0,0.f);put(w+0x6aa0,2.f);assert(!ssc_record::active_round(base,2));put(w+0x6aa0,NAN);assert(!ssc_record::active_round(base,2));put(w+0x6aa0,0.f);put(w+0x485,uint8_t(1));assert(!ssc_record::active_round(base,2));put(w+0x485,uint8_t(0));assert(!ssc_record::active_round(base,1));VirtualFree(reinterpret_cast<void*>(base),0,MEM_RELEASE);
 using namespace ssc_combat;Counter c;Context o;o.valid=o.active=true;o.session=1;o.round=1;c.fired(o,1);assert(!c.complete);o.active=false;o.preparing=true;c.observe(o);o.active=true;o.preparing=false;c.fired(o,8);c.hit(o,0,12.f);assert(c.complete&&c.totals.shots==1&&c.totals.projectiles==8&&c.totals.player_hits==1);c.hit(o,2,5.f);assert(c.totals.npc_hits==1&&c.totals.impact==17);c.hit(o,0,NAN);c.hit(o,0,-1);assert(c.totals.hits==2);o.active=false;o.ending=true;c.observe(o);o.ending=false;o.active=true;c.fired(o,1);assert(c.totals.shots==1);++o.round;c.fired(o,2);assert(c.complete&&c.totals.shots==1&&c.totals.projectiles==2);o.session=2;c.fired(o,1);assert(!c.complete);o.valid=false;c.observe(o);assert(!c.session);
 std::cout<<"PASS: bounded string reads, inaccessible memory, final-round recording gates and combat lifecycle\n";
}
