#include "../runtime/overlay.cpp"
#include <cassert>
static int seen_icon=-1,seen_width=0;static uintptr_t seen_atlas=0;static GLuint seen_texture=0;
static void fake_draw(uintptr_t object,uintptr_t atlas,float x,float y,float w,float h,int icon,char flip,int blend,float alpha,uint32_t r,uint32_t g,uint32_t b,char depth){assert(object==123&&x==2&&y==3&&w==64&&h==64&&flip==0&&blend==1&&alpha==.5f&&r==7&&g==8&&b==9&&depth==1);seen_icon=icon;seen_atlas=atlas;std::memcpy(&seen_width,reinterpret_cast<void*>(atlas+0x24),4);std::memcpy(&seen_texture,reinterpret_cast<void*>(atlas+0x20),4);}
int main(int argc,char** argv){assert(argc==3);using namespace ssc_wheel_images;auto dir=std::filesystem::path(argv[2]);std::filesystem::create_directories(dir);assert(import_file(argv[1],dir,1));assert(images[1].size()==64*64*4);assert(images[1][3]==0);auto center=(32*64+32)*4;assert(images[1][center]>240&&images[1][center+3]>=120&&images[1][center+3]<=135);auto old=images[1];assert(!import_file(dir/"missing.png",dir,1)&&images[1]==old);load(dir);assert(images[1]==old);
 WNDCLASSW wc{};wc.style=CS_OWNDC;wc.lpfnWndProc=DefWindowProcW;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"SSCWheelImageTest";assert(RegisterClassW(&wc));HWND window=CreateWindowW(wc.lpszClassName,L"",WS_POPUP,0,0,64,64,nullptr,nullptr,wc.hInstance,nullptr);assert(window);HDC dc=GetDC(window);PIXELFORMATDESCRIPTOR pfd{};pfd.nSize=sizeof(pfd);pfd.nVersion=1;pfd.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;pfd.iPixelType=PFD_TYPE_RGBA;pfd.cColorBits=32;int format=ChoosePixelFormat(dc,&pfd);assert(format&&SetPixelFormat(dc,format,&pfd));HGLRC gl=wglCreateContext(dc);assert(gl&&wglMakeCurrent(dc,gl));
 std::array<unsigned char,0x38> descriptor{};auto address=reinterpret_cast<uintptr_t>(descriptor.data());original=fake_draw;fallback[1]=6;
 draw(123,address,2,3,64,64,0x205,0,1,.5f,7,8,9,1);assert(seen_icon==0x205&&seen_atlas==address);
 glPixelStorei(GL_UNPACK_ROW_LENGTH,7);draw(123,address,2,3,64,64,tag+1,0,1,.5f,7,8,9,1);assert(seen_icon==1&&seen_atlas!=address&&seen_width==2048&&seen_texture);GLint row=0;glGetIntegerv(GL_UNPACK_ROW_LENGTH,&row);assert(row==7);
 glBindTexture(GL_TEXTURE_2D,seen_texture);std::vector<unsigned char> pixels(2048*2048*4);glGetTexImage(GL_TEXTURE_2D,0,GL_RGBA,GL_UNSIGNED_BYTE,pixels.data());assert(glGetError()==GL_NO_ERROR);assert(pixels[((32*2048)+64+32)*4]>240);
 images[1].clear();draw(123,address,2,3,64,64,tag+1,0,1,.5f,7,8,9,1);assert(seen_icon==0x206&&seen_atlas==address);
 wglMakeCurrent(nullptr,nullptr);wglDeleteContext(gl);ReleaseDC(window,dc);DestroyWindow(window);UnregisterClassW(wc.lpszClassName,wc.hInstance);std::puts("PASS: image decode/aspect/transparency/persistence, bounded failure, native icon bridge arguments, custom atlas and original fallback");
}
